Allow asynchronous RequestModifiers
onevcat/Kingfisher pull request #1501
Opened 2020-08-24 09:25 UTC by hoaCed

Hi 👋 
This allows the RequestModifier to run asynchronously. This might be useful for refreshing auth headers before sending a request for example.
However, as a consequence, the DownloadTask chain has to be modified to use completions.

2020-08-28 09:07 UTC, denisPoifol requested changes
This seems ok on a functional level but I would tweak one ore two things :
- taskHandler closures should never be nil
- this change is leading to a new major version so it might be the opportunity to remove deprecated methods.

2020-08-28 09:07 UTC, denisPoifol commented on Sources/General/KingfisherManager.swift
> +        taskHandler: ((DownloadTask.WrappedTask?) -> Void)? = nil,
Same thing here

2020-08-28 09:07 UTC, denisPoifol commented on Sources/Networking/ImageDownloader.swift
> +        taskHandler: ((DownloadTask?) -> Void)? = nil,
Same thing here

2020-08-28 09:07 UTC, denisPoifol commented on Sources/Networking/ImageDownloader.swift
> +                               taskHandler: ((DownloadTask?) -> Void)? = nil,
Same thing here

2020-08-28 09:07 UTC, denisPoifol commented on Sources/Networking/ImageDownloader.swift
> +        taskHandler: ((DownloadTask?) -> Void)? = nil,
Same thing here

2020-08-29 01:59 UTC, onevcat commented
Hey, @hoaCed 

Thanks a lot for this PR. It looks nice itself and I am sure it would do its work perfectly!

However, it changed the public interface in a non-trivial way and obviously requires a major update version. I am not quite sure if this worths enough to apply these changes now since there is an easy enough way to separate your async operation and get what you want before sending them to Kingfisher's request modifier. It would keep the implementation of Kingfisher to keep simple and make the logic (especially how to handle the async error) clearly.

So, in my opinion, it is a low priority. I will leave this PR open for a while before we can find some other things requiring a major update. I think it might be a better chance to apply these too.

Thank you for your hard work!

2021-01-01 01:56 UTC, onevcat commented
Thanks again for this PR and all the contribution! I've implemented an async request modifier with a bit of trade-off. Now it does not change the current released APIs, but with a callback block to get back the `DownloadTask`. Good news is the download task is not being used for most of times so I think it worths to do this tradeoff.

I will merge #1589 instead and release a new version containing this.

2021-01-01 01:56 UTC, closed without merging